### ISSUE TITLE
Radarr POST movie - Expectation Failed

### ISSUE THREAD

**Issue by andrew-bengier** [Panzer1119/radarr4j#1]
question - I am trying to connect to Radarr via the api and am stuck. When i use the GET ```api/v3/lookup``` endpoint i get back an appropriate response object, but when i try to then add it using the POST ```api/v3/movie``` endpoint i continually get "BAD REQUEST: Expectation Failed" as a response. Is there any insight you can help provide? 

example tmdbId: 370172
returns:
```
Movie: {
  "id": 0,
  "tmdbId": "370172",
  "folder": "No Time to Die (2021)",
  "rootFolderPath": "/movies",
  "title": "No Time to Die",
  "titleSlug": "370172",
  "cleanTitle": "notimetodie",
  "year": 2021,
  "overview": "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
  "images": [
    {
      "coverType": "poster",
      "url": "https://image.tmdb.org/t/p/original/xp5s0aLHZuoHH64DDYNy0jLRrRH.jpg"
    },
    {
      "coverType": "fanart",
      "url": "https://image.tmdb.org/t/p/original/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg"
    }
  ],
  "tags": [],
  "status": "released",
  "hasFile": false,
  "sizeOnDisk": 0,
  "qualityProfileId": 0,
  "monitored": true,
  "isAvailable": false,
  "minimumAvailability": "released",
  "addOptions": {
    "searchForMovie": "true"
  }
}
```

**Comment by Panzer1119** [comment]
Do you mean `/api/v3/movie/lookup`?

That endpoint returns a List of Movies, so maybe you used an JSON Array in the Body to post to `/api/v3/movie`, which wants a single Movie?

**Comment by andrew-bengier** [comment]
Ah apologies - the endpoint i was using is ```api/v3/movie/lookup/tmdb?tmdbId=370172``` -> that is returning a single movie, which is what im using as the body in the POST for ```/api/v3/movie```

**Comment by Panzer1119** [comment]
Have you read RhinoRhys/radarr-collections#113 already, maybe that's a problem?

And also, do you use this library (which is mainly auto-generated code), or are you asking about The Radarr API in general?

**Comment by andrew-bengier** [comment]
yes i read that post and thought about the possibilities of type issues, but in that library there is an example with a totally stripped down "movie" that have maybe 5 attributes that i also tried. My question is mostly general API since i'm not using any library - i can provide code examples if that would help... I also find it frustrating that as a BAD REQUEST there isn't anywhere i can look for logs on the radarr side or a better response body to tell me the expectation that failed...

**Comment by Panzer1119** [comment]
You could try to set the log level of Radarr to trace in the general settings and maybe that would help.

And then execute your Requests.

(don't forget to switch back to info after testing it)

**Comment by Panzer1119** [comment]
> Ah apologies - the endpoint i was using is `api/v3/movie/lookup/tmdb?tmdbId=370172` -> that is returning a single movie, which is what im using as the body in the POST for `/api/v3/movie`

I just tried it locally and posted your JSON to `/api/v3/movie` and it told me (with trace log level enabled) that it can't convert the boolean from `addOptions.searchForMovie` and when i removed the quotes it worked (if you also supply a valid `qualityProfileId`)

**Comment by andrew-bengier** [comment]
I am trying now with a proper qualityProfileId, finally saw that in the logs
